/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.util.ArrayList;

/**
 *
 * @author Pablo Martin
 */
public class interfaz extends javax.swing.JFrame {
conexionMain gestor = new conexionMain();

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
//        rellenaComboxPelis();
        reseteaValoresBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        añadir_director = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        L_nacimiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        delete_director = new javax.swing.JButton();
        deleteDirectorBox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        apellidoDirector1 = new javax.swing.JTextField();
        apellidoDirector2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nombre_Director = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        apellidoDirector3 = new javax.swing.JTextField();
        apellidoDirector4 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nombre_Director1 = new javax.swing.JTextField();
        L_nacimiento1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Actualizar_box_director = new javax.swing.JComboBox<>();
        actualizaDirectores = new javax.swing.JButton();
        Mostrar_director = new javax.swing.JButton();
        muestraDirector = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        ID_actualizar1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        ID_actualizar2 = new javax.swing.JTextField();
        closeConection = new javax.swing.JButton();
        openConection = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        nombre_actualizar = new javax.swing.JTextField();
        t_genero1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        titulo_text1 = new javax.swing.JTextField();
        seleccionaDirectorBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        add_film = new javax.swing.JButton();
        seleccionaActorBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        t_genero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        deleteBox = new javax.swing.JComboBox<>();
        delete_film = new javax.swing.JButton();
        muestra_pelis = new javax.swing.JComboBox<>();
        Mostrar_pelis = new javax.swing.JButton();
        Actualizar_box = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ID_actualizar = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        añadir_actor = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        ciudadActor2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        delete_Actor = new javax.swing.JButton();
        deleteActorBox = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        apellidoActor3 = new javax.swing.JTextField();
        apellidoActor4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        nombre_actor2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        apellidoActor1 = new javax.swing.JTextField();
        apellidoActor2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        nombre_actor = new javax.swing.JTextField();
        ciudadActor = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Actualizar_box_actor = new javax.swing.JComboBox<>();
        actualiza_actor = new javax.swing.JButton();
        mostrarActor_box1 = new javax.swing.JComboBox<>();
        Mostrar_actor = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        ID_actualizar3 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        ID_actualizar4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Añade aquí los datos del director a actualizar:");

        añadir_director.setText("Añadir Director");
        añadir_director.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        añadir_director.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadir_directorActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Selecciona el directo al que se quiera eliminar:");

        L_nacimiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lugar nacimiento:");

        delete_director.setText("Borrar director");
        delete_director.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        delete_director.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_directorActionPerformed(evt);
            }
        });

        deleteDirectorBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteDirectorBox.setName(""); // NOI18N
        deleteDirectorBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDirectorBoxActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("2ºApellido");

        apellidoDirector1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        apellidoDirector2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("1ºApellido:");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nombre:");

        nombre_Director.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("2ºApellido");

        apellidoDirector3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        apellidoDirector4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("1ºApellido:");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nombre:");

        nombre_Director1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        L_nacimiento1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Lugar nacimiento:");

        Actualizar_box_director.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Actualizar_box_director.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar_box_directorActionPerformed(evt);
            }
        });

        actualizaDirectores.setText("Actualizar director");
        actualizaDirectores.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        actualizaDirectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizaDirectoresActionPerformed(evt);
            }
        });

        Mostrar_director.setText("Mostrar director");
        Mostrar_director.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mostrar_director.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_directorActionPerformed(evt);
            }
        });

        muestraDirector.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        muestraDirector.setName(""); // NOI18N
        muestraDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muestraDirectorActionPerformed(evt);
            }
        });

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("ID:");

        ID_actualizar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("ID:");

        ID_actualizar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(añadir_director, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Actualizar_box_director, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(actualizaDirectores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(muestraDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Mostrar_director, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(apellidoDirector2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(apellidoDirector1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_Director, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(L_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deleteDirectorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delete_director, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(apellidoDirector4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(apellidoDirector3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_Director1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ID_actualizar1)
                            .addComponent(L_nacimiento1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(ID_actualizar2))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Actualizar_box_director)
                    .addComponent(actualizaDirectores, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(nombre_Director1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(apellidoDirector3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(apellidoDirector4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(L_nacimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(ID_actualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(ID_actualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(nombre_Director, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(apellidoDirector1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(apellidoDirector2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(L_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(añadir_director, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delete_director, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteDirectorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mostrar_director, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(muestraDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        closeConection.setText("Cerrar conexion");
        closeConection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        closeConection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeConectionActionPerformed(evt);
            }
        });

        openConection.setText("Abrir conexion");
        openConection.setBorder(new javax.swing.border.MatteBorder(null));
        openConection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openConectionActionPerformed(evt);
            }
        });

        mensaje.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Añade aquí los datos a actualizar de la canción");

        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("Titulo: ");

        nombre_actualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        t_genero1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Género:");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");

        ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Añade aquí los datos de la pelicula a añadir:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Titulo: ");

        titulo_text1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        seleccionaDirectorBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        seleccionaDirectorBox.setName(""); // NOI18N
        seleccionaDirectorBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionaDirectorBoxActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Selecciona el director al que pertenece la pelicula:");

        add_film.setText("Añadir pelicula");
        add_film.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add_film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_filmActionPerformed(evt);
            }
        });

        seleccionaActorBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        seleccionaActorBox.setName(""); // NOI18N
        seleccionaActorBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionaActorBoxActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Selecciona el actor al que pertenece la pelicula:");

        t_genero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Género:");

        deleteBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBoxActionPerformed(evt);
            }
        });

        delete_film.setText("Borrar pelicula");
        delete_film.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        delete_film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_filmActionPerformed(evt);
            }
        });

        muestra_pelis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        muestra_pelis.setName(""); // NOI18N
        muestra_pelis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muestra_pelisActionPerformed(evt);
            }
        });

        Mostrar_pelis.setText("Mostrar peliculas");
        Mostrar_pelis.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mostrar_pelis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_pelisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seleccionaDirectorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(seleccionaActorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_film, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(ID))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(t_genero)
                                .addComponent(titulo_text1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(muestra_pelis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteBox, 0, 86, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mostrar_pelis, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_film, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(titulo_text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccionaDirectorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionaActorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add_film)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delete_film, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(muestra_pelis, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(Mostrar_pelis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Actualizar_box.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Actualizar_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar_boxActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar pelicula");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID:");

        ID_actualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Actualizar_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(ID_actualizar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(t_genero1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(nombre_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Actualizar_box)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ID_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label)
                    .addComponent(nombre_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(t_genero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(102, 102, 102))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Añade aquí los datos del director a actualizar:");

        añadir_actor.setText("Añadir Actor");
        añadir_actor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        añadir_actor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadir_actorActionPerformed(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Selecciona el directo al que se quiera eliminar:");

        ciudadActor2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Lugar nacimiento:");

        delete_Actor.setText("Borrar Actor");
        delete_Actor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        delete_Actor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_ActorActionPerformed(evt);
            }
        });

        deleteActorBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteActorBox.setName(""); // NOI18N
        deleteActorBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActorBoxActionPerformed(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("2ºApellido");

        apellidoActor3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        apellidoActor4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("1ºApellido:");

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Nombre:");

        nombre_actor2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("2ºApellido");

        apellidoActor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        apellidoActor2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("1ºApellido:");

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Nombre:");

        nombre_actor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ciudadActor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Lugar nacimiento:");

        Actualizar_box_actor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Actualizar_box_actor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar_box_actorActionPerformed(evt);
            }
        });

        actualiza_actor.setText("Actualizar actor");
        actualiza_actor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        actualiza_actor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiza_actorActionPerformed(evt);
            }
        });

        mostrarActor_box1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mostrarActor_box1.setName(""); // NOI18N
        mostrarActor_box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActor_box1ActionPerformed(evt);
            }
        });

        Mostrar_actor.setText("Mostrar actores");
        Mostrar_actor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mostrar_actor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_actorActionPerformed(evt);
            }
        });

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("ID:");

        ID_actualizar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("ID:");

        ID_actualizar4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(añadir_actor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Actualizar_box_actor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(actualiza_actor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(apellidoActor4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(apellidoActor3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_actor2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ciudadActor2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(deleteActorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delete_Actor, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(apellidoActor2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(apellidoActor1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_actor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(mostrarActor_box1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Mostrar_actor, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ciudadActor, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(ID_actualizar3)
                            .addComponent(ID_actualizar4))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Actualizar_box_actor)
                    .addComponent(actualiza_actor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(nombre_actor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(apellidoActor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(apellidoActor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(ciudadActor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(ID_actualizar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(ID_actualizar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(nombre_actor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(apellidoActor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(apellidoActor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(ciudadActor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(añadir_actor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delete_Actor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteActorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Mostrar_actor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mostrarActor_box1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(openConection, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(closeConection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 187, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(closeConection, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(openConection, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadir_directorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadir_directorActionPerformed
        //este boton lo que hace es que una vez el usuario introduce titulo, un autor y una fecha de lanzamiento
        //se introduzca dentro de la base de datos
        gestor.insertarDirector(this.ID_actualizar3.getText(),this.nombre_Director.getText(), this.apellidoDirector1.getText(), this.apellidoDirector2.getText(),L_nacimiento.getText());
        limpiaCajas();
        reseteaValoresBox();
    }//GEN-LAST:event_añadir_directorActionPerformed

    private void delete_directorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_directorActionPerformed
        //Este metodo borra el director que se haya seleccionado en el comboBox
        gestor.deleteDirector(deleteDirectorBox.getSelectedItem().toString());
        reseteaValoresBox();
        limpiaCajas();
    }//GEN-LAST:event_delete_directorActionPerformed

    private void deleteDirectorBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDirectorBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteDirectorBoxActionPerformed

    private void Actualizar_box_directorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar_box_directorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Actualizar_box_directorActionPerformed

    private void actualizaDirectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizaDirectoresActionPerformed
        //Este metodo actualiza los datos de la BBDD de la tabla directores, se ha de introducir los valores a modificar
        gestor.actualizaDirectores( Actualizar_box_director.getSelectedItem().toString(),nombre_Director1.getText(),apellidoDirector3.getText() , apellidoDirector4.getText(),L_nacimiento1.getText());
        limpiaCajas();
        reseteaValoresBox();
    }//GEN-LAST:event_actualizaDirectoresActionPerformed

    private void Mostrar_directorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_directorActionPerformed
    jTextArea1.setText(gestor.consulta_directores(muestraDirector.getSelectedItem().toString()));
    }//GEN-LAST:event_Mostrar_directorActionPerformed

    private void Mostrar_pelisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_pelisActionPerformed
        // Este boton muestra las canciones de cada album, previamente hay que seleccionar
        //el album del comboBox para mostrar las canciones
//        System.out.println(Mostrar_pelis.getText()));
        jTextArea1.setText(gestor.muestraPelis(muestra_pelis.getSelectedItem().toString()));
    }//GEN-LAST:event_Mostrar_pelisActionPerformed

    private void closeConectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeConectionActionPerformed
        // este boton cierra la conexion con la base de datos
        if(gestor.cerrarConexion() == 0){
            mensaje.setText("desconexion realizada con exito");
            System.out.println("desconectado de la base de datos");
            openConection.setEnabled(true);
            closeConection.setEnabled(false);
        }
        else{
            System.out.println("no se ha podido desconectar de la base de datos");
        }
    }//GEN-LAST:event_closeConectionActionPerformed

    private void openConectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openConectionActionPerformed
        // este boton abre la conexion de la base de datos
            gestor.GestorConexion();
//            mensaje.setText("Conexion realizada con exito");
            openConection.setEnabled(false);
            closeConection.setEnabled(true);
//            rellenaComboxPelis();
            //se introduce el metodo para limpiar las cajas de texto
            reseteaValoresBox();
       
    }//GEN-LAST:event_openConectionActionPerformed

    private void seleccionaDirectorBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionaDirectorBoxActionPerformed
        //TODO add your handling code here:
    }//GEN-LAST:event_seleccionaDirectorBoxActionPerformed

    private void add_filmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_filmActionPerformed
        //este boton añade una nueva pelicula, existe un comboBox que muestra los actores y directores y debemos seleccionar uno de cada para poder introducir
        //la pelicula dentro de la bbdd, ademas coge lo introducido por el usuario como el nombre fecha de lanzamiento y genero
                gestor.insertarPelicula(this.ID.getText(),this.titulo_text1.getText(), this.t_genero.getText(),this.seleccionaDirectorBox.getSelectedIndex(),this.seleccionaActorBox.getSelectedIndex());
                limpiaCajas();
                reseteaValoresBox();
    }//GEN-LAST:event_add_filmActionPerformed

    private void seleccionaActorBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionaActorBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionaActorBoxActionPerformed

    private void deleteBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBoxActionPerformed

    private void delete_filmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_filmActionPerformed
        //este boton permite borrar cualquier pelicula, simplemente hay que
        //seleccionar la pelicula del comboBox
        gestor.deleteFilm(deleteBox.getSelectedItem().toString());
        reseteaValoresBox();
        limpiaCajas();
    }//GEN-LAST:event_delete_filmActionPerformed

    private void Actualizar_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Actualizar_boxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //este boton tiene la funcion de actualizar una pelicula, coge el titulo de la peli
        // en el comboBox, y el resto de valores lo introduce el ususario introduce el usuario

     
                gestor.actualizaPelis(Actualizar_box.getSelectedItem().toString(),nombre_actualizar.getText(),t_genero1.getText());
                limpiaCajas();
                reseteaValoresBox();
           
    }//GEN-LAST:event_jButton2ActionPerformed

    private void añadir_actorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadir_actorActionPerformed
        //Este metodo añade un director nuevo con sus valores correspondientes
        gestor.insertarActor(this.ID_actualizar4.getText(),this.nombre_actor2.getText(), this.apellidoActor3.getText(), this.apellidoActor4.getText(),ciudadActor2.getText());
        limpiaCajas();
        reseteaValoresBox();
    }//GEN-LAST:event_añadir_actorActionPerformed

    private void delete_ActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_ActorActionPerformed
        //Este metodo borra por completo el actor seleccionado
        gestor.deleteActor(deleteActorBox.getSelectedItem().toString());
        reseteaValoresBox();
        limpiaCajas();
    }//GEN-LAST:event_delete_ActorActionPerformed

    private void deleteActorBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActorBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActorBoxActionPerformed

    private void Actualizar_box_actorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar_box_actorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Actualizar_box_actorActionPerformed

    private void actualiza_actorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiza_actorActionPerformed
        //Este metodo actualiza los atributos de los actores
        gestor.actualizaActores(Actualizar_box_actor.getSelectedItem().toString(),nombre_actor.getText(),apellidoActor1.getText() , apellidoActor2.getText(),ciudadActor.getText());
        limpiaCajas();
        reseteaValoresBox();
    }//GEN-LAST:event_actualiza_actorActionPerformed

    private void mostrarActor_box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActor_box1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarActor_box1ActionPerformed

    private void Mostrar_actorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_actorActionPerformed
        jTextArea1.setText(gestor.consulta_actores(mostrarActor_box1.getSelectedItem().toString()));
    }//GEN-LAST:event_Mostrar_actorActionPerformed

    private void muestraDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muestraDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_muestraDirectorActionPerformed

    private void muestra_pelisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muestra_pelisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_muestra_pelisActionPerformed
 public void reseteaValoresBox() {
           //En este metodo el objetivo es añadir un item en blanco, que sera el
           //item inicial, dandole un toque estetico, a parte busca tambien implementar
           //dentro del comboBox todas las peliculas, directores o actores dependiendo 
           //del comboBox que se deba usar, despues se usa el remove item para 
           //una vez se añada, borre o modifique un album/cancion el cambio se muestre 
           //dentro del comboBox y sin que se repita.
        muestraDirector.removeAllItems();
        muestra_pelis.removeAllItems();
        Actualizar_box.removeAllItems();
        deleteBox.removeAllItems();
        seleccionaDirectorBox.removeAllItems();
        seleccionaActorBox.removeAllItems();
        muestra_pelis.removeAllItems();
        Actualizar_box_director.removeAllItems();
        deleteDirectorBox.removeAllItems();
        deleteActorBox.removeAllItems();
        Actualizar_box_actor.removeAllItems();
        mostrarActor_box1.removeAllItems();
        mostrarActor_box1.addItem("");
        Actualizar_box_director.addItem("");
        deleteDirectorBox.addItem("");
        deleteActorBox.addItem("");
        Actualizar_box_actor.addItem("");
        muestra_pelis.addItem("");
        Actualizar_box.addItem("");
        deleteBox.addItem("");
        seleccionaDirectorBox.addItem("");
        seleccionaActorBox.addItem("");
        muestra_pelis.addItem("");
        muestraDirector.addItem("");
       // estos bucles sirven para meter en los comboBox los actores, directores y peliculas 
        for (int i = 0; i < gestor.consulta_actores().size(); i++) {
//            muestra_pelis.addItem(gestor.consulta_actores().get(i));
            seleccionaActorBox.addItem(gestor.consulta_actores().get(i));
           deleteActorBox.addItem(gestor.consulta_actores().get(i));
           Actualizar_box_actor.addItem(gestor.consulta_actores().get(i));
            mostrarActor_box1.addItem(gestor.consulta_actores().get(i));
       }
        for (int i = 0; i < gestor.consulta_peliculas().size(); i++) {
            Actualizar_box.addItem(gestor.consulta_peliculas().get(i));
            deleteBox.addItem(gestor.consulta_peliculas().get(i));
            muestra_pelis.addItem(gestor.consulta_peliculas().get(i));
        }
        for (int i = 0; i < gestor.consulta_directores().size(); i++) {
            seleccionaDirectorBox.addItem(gestor.consulta_directores().get(i));
          Actualizar_box_director.addItem(gestor.consulta_directores().get(i));
          deleteDirectorBox.addItem(gestor.consulta_directores().get(i));
          muestraDirector.addItem(gestor.consulta_directores().get(i));
        }
      
    }
// private void rellenaComboxPelis(){
//     mostrarCancion_box.removeAllItems();
//     ArrayList<String> pelis = new ArrayList<String>();
//     pelis = gestor.consulta_peliculas();
//     for(int i = 0 ; i < pelis.size();i++){
//         mostrarCancion_box.addItem(pelis.get(i));
//     }
// }
   public void limpiaCajas(){
           //este metodo es de lo mas sencillo, lo unico que hace es vaciar de 
           //texto los sitios donde se deben poner los datos necesarios para 
           //realizar cambios en la BBDD, y no tener que estar borrando todo el rato
            ciudadActor2.setText("");
            ciudadActor.setText("");
            ID.setText("");
            apellidoActor1.setText("");
            apellidoActor2.setText("");
            apellidoActor3.setText("");
            apellidoActor4.setText("");
            apellidoDirector1.setText("");
            apellidoDirector2.setText("");
            apellidoDirector3.setText("");
            apellidoDirector4.setText("");
            L_nacimiento1.setText("");
            t_genero.setText("");
            L_nacimiento.setText("");
            titulo_text1.setText("");
            ID_actualizar.setText("");
            nombre_actualizar.setText("");
            t_genero1.setText("");
            nombre_Director.setText("");
            nombre_Director1.setText("");
            nombre_actor.setText("");
            nombre_actor2.setText("");
            ID.setText("");
            ID_actualizar.setText("");
            ID_actualizar1.setText("");
            ID_actualizar2.setText("");
            ID_actualizar3.setText("");
            ID_actualizar4.setText("");
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Actualizar_box;
    private javax.swing.JComboBox<String> Actualizar_box_actor;
    private javax.swing.JComboBox<String> Actualizar_box_director;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField ID_actualizar;
    private javax.swing.JTextField ID_actualizar1;
    private javax.swing.JTextField ID_actualizar2;
    private javax.swing.JTextField ID_actualizar3;
    private javax.swing.JTextField ID_actualizar4;
    private javax.swing.JTextField L_nacimiento;
    private javax.swing.JTextField L_nacimiento1;
    private javax.swing.JButton Mostrar_actor;
    private javax.swing.JButton Mostrar_director;
    private javax.swing.JButton Mostrar_pelis;
    private javax.swing.JButton actualizaDirectores;
    private javax.swing.JButton actualiza_actor;
    private javax.swing.JButton add_film;
    private javax.swing.JTextField apellidoActor1;
    private javax.swing.JTextField apellidoActor2;
    private javax.swing.JTextField apellidoActor3;
    private javax.swing.JTextField apellidoActor4;
    private javax.swing.JTextField apellidoDirector1;
    private javax.swing.JTextField apellidoDirector2;
    private javax.swing.JTextField apellidoDirector3;
    private javax.swing.JTextField apellidoDirector4;
    private javax.swing.JButton añadir_actor;
    private javax.swing.JButton añadir_director;
    private javax.swing.JTextField ciudadActor;
    private javax.swing.JTextField ciudadActor2;
    private javax.swing.JButton closeConection;
    private javax.swing.JComboBox<String> deleteActorBox;
    private javax.swing.JComboBox<String> deleteBox;
    private javax.swing.JComboBox<String> deleteDirectorBox;
    private javax.swing.JButton delete_Actor;
    private javax.swing.JButton delete_director;
    private javax.swing.JButton delete_film;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel mensaje;
    private javax.swing.JComboBox<String> mostrarActor_box1;
    private javax.swing.JComboBox<String> muestraDirector;
    private javax.swing.JComboBox<String> muestra_pelis;
    private javax.swing.JTextField nombre_Director;
    private javax.swing.JTextField nombre_Director1;
    private javax.swing.JTextField nombre_actor;
    private javax.swing.JTextField nombre_actor2;
    private javax.swing.JTextField nombre_actualizar;
    private javax.swing.JButton openConection;
    private javax.swing.JComboBox<String> seleccionaActorBox;
    private javax.swing.JComboBox<String> seleccionaDirectorBox;
    private javax.swing.JTextField t_genero;
    private javax.swing.JTextField t_genero1;
    private javax.swing.JTextField titulo_text1;
    // End of variables declaration//GEN-END:variables
}
